# Example config
server:
  applicationConnectors:
    - type: http
      port: 8080
    - type: https
      port: 4443
      keyStorePath: conf/keystore.dev.jks
      keyStorePassword: your_secret
      certAlias: myservercert
      validateCerts: false
      validatePeers: false

  adminConnectors:
    - type: http
      port: 8081
#  requestLog:
#    appenders: []

auth: your_token   # obtained from DevBot when running: show bot <name>
cryptoDir: ./data

adminHandle: e0b9cdae-eab0-11e7-9ecf-f3c037eda9b8